### ISSUE TITLE
Feature not resolvable?

### ISSUE THREAD

**Issue by tfenster** [dev-wasm/dev-wasm-feature#1]
I have an existing devcontainer that works fine (.NET 7, but I don't think that matters?). When I try to add the dev-wasm-feature like this in devcontainer.json:

```
	"features": {
		"devwasm.azurecr.io/dev-wasm/dev-wasm-feature/wasmtime-wasi:0": {}
	}
```

and then rebuild the container, I get this error message:

```
[2022-12-29T15:41:55.270Z] * Processing feature: devwasm.azurecr.io/dev-wasm/dev-wasm-feature/wasmtime-wasi:0
[2022-12-29T15:41:55.271Z] No authentication credentials found for registry 'devwasm.azurecr.io'.
[2022-12-29T15:41:55.271Z] No authentication credentials found for registry 'devwasm.azurecr.io'.
[2022-12-29T15:41:56.658Z] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[2022-12-29T15:41:56.658Z] Github feature.
[2022-12-29T15:41:56.658Z] Could not resolve Feature 'devwasm.azurecr.io/dev-wasm/dev-wasm-feature/wasmtime-wasi:0'.  Ensure the Feature is published and accessible from your current environment.
[2022-12-29T15:41:56.660Z] Error: Failed to process feature devwasm.azurecr.io/dev-wasm/dev-wasm-feature/wasmtime-wasi:0
[2022-12-29T15:41:56.660Z]     at one (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1777:3059)
[2022-12-29T15:41:56.661Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-12-29T15:41:56.661Z]     at async nm (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1777:2227)
[2022-12-29T15:41:56.662Z]     at async Mf (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1779:1383)
[2022-12-29T15:41:56.662Z]     at async am (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1779:308)
[2022-12-29T15:41:56.662Z]     at async EF (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1865:2001)
[2022-12-29T15:41:56.663Z]     at async x7 (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1865:901)
[2022-12-29T15:41:56.663Z]     at async oie (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1871:2093)
[2022-12-29T15:41:56.663Z]     at async qf (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1871:3239)
[2022-12-29T15:41:56.663Z]     at async Mse (c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js:1995:16211)
[2022-12-29T15:41:56.687Z] Stop (3520 ms): Run: C:\Users\tfenster\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\tfenster\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\tfenster\github\planner-exandimport-wasm --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\tfenster\github\planner-exandimport-wasm --log-level debug --log-format json --config c:\Users\tfenster\github\planner-exandimport-wasm\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-12-29T15:41:56.688Z] Exit code 1
[2022-12-29T15:41:56.703Z] Command failed: C:\Users\tfenster\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\tfenster\.vscode\extensions\ms-vscode-remote.remote-containers-0.268.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\tfenster\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\tfenster\github\planner-exandimport-wasm --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\tfenster\github\planner-exandimport-wasm --log-level debug --log-format json --config c:\Users\tfenster\github\planner-exandimport-wasm\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-12-29T15:41:56.704Z] Exit code 1
```

Am I missing something? Is this not the intended use?

**Comment by brendandburns** [comment]
Unfortunately, devcontainer CLI tooling before `0.27.0` had a bug so that it doesn't support repositories other than `ghcr.io` 

Please upgrade to `0.27.0` or later and try again.

Thanks!

**Comment by tfenster** [comment]
Confirmed, with that update it now works! Thanks
