### ISSUE TITLE
cannot install wasm feature since it failed to download

### ISSUE THREAD

**Issue by pascal456** [dev-wasm/dev-wasm-feature#8]
I tried with all the suggested versions ("9.0.4", "10.0.1", "11.0.1")

dev container error log:
```
=> ERROR [dev_containers_target_stage 6/9] RUN --mount=type=bind,from=de  0.9s
------
 > [dev_containers_target_stage 6/9] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=wasmtime-wasi_1,target=/tmp/build-features-src/wasmtime-wasi_1     cp -ar /tmp/build-features-src/wasmtime-wasi_1 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/wasmtime-wasi_1  && cd /tmp/dev-container-features/wasmtime-wasi_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/wasmtime-wasi_1:
0.555 ===========================================================================
[2023-08-12T14:47:50.427Z] 0.555 Feature       : Wasmtime runtime and WASI SDK
0.555 Description   : Installs the wasmtime runtime for WebAssembly and the WebAssembly System Interface (WASI) SDK
0.555 Id            : devwasm.azurecr.io/dev-wasm/dev-wasm-feature/wasmtime-wasi
0.555 Version       : 0.0.10
0.555 Documentation : https://github.com/dev-wasm/dev-wasm-feature
0.555 Options       :
0.555     VERSION="20"
0.555     WASMTIME_VERSION="11.0.1"
0.555     WIT_VERSION="0.8.0"
0.555     LOCATION="/usr/local/lib"
0.555 ===========================================================================
0.559 
0.559 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
0.559 
0.567 libc6 is already the newest version (2.36-9+deb12u1).
0.567 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
0.570   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
0.570                                  Dload  Upload   Total   Spent    Left  Speed
0.570 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15085  100 15085    0     0   226k      0 --:--:-- --:--:-- --:--:--  230k
0.639   Installing Wasmtime version 11.0.1
0.639     Checking for existing Wasmtime installation
0.640     Fetching archive for Linux, version 11.0.1
0.641 https://github.com/bytecodealliance/wasmtime/releases/download/11.0.1/wasmtime-11.0.1-x86_64-linux.tar.xz 
0.860 #=#=#                                                                         
curl: (22) The requested URL returned error: 404
0.869 
0.871 Error: Could not download Wasmtime version '11.0.1'. See https://github.com/bytecodealliance/wasmtime/releases for a list of available releases
0.871 
0.871 cp: cannot stat '/root/.wasmtime/bin/wasmtime': No such file or directory
0.872 ERROR: Feature "Wasmtime runtime and WASI SDK" (devwasm.azurecr.io/dev-wasm/dev-wasm-feature/wasmtime-wasi) failed to install! Look at the documentation at https://github.com/dev-wasm/dev-wasm-feature for help troubleshooting this error.
------
Dockerfile.extended:33
--------------------
  32 |     
  33 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=wasmtime-wasi_1,target=/tmp/build-features-src/wasmtime-wasi_1 \
  34 | >>>     cp -ar /tmp/build-features-src/wasmtime-wasi_1 /tmp/dev-container-features \
  35 | >>>  && chmod -R 0755 /tmp/dev-container-features/wasmtime-wasi_1 \
  36 | >>>  && cd /tmp/dev-container-features/wasmtime-wasi_1 \
  37 | >>>  && chmod +x ./devcontainer-features-install.sh \
  38 | >>>  && ./devcontainer-features-install.sh \
  39 | >>>  && rm -rf /tmp/dev-container-features/wasmtime-wasi_1
  40 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/wasmtime-wasi_1 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/wasmtime-wasi_1  && cd /tmp/dev-container-features/wasmtime-wasi_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/wasmtime-wasi_1" did not complete successfully: exit code: 1
[2023-08-12T14:47:50.432Z] Stop (104632 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-ubuntu/container-features/0.50.0-1691851552142 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-linuxfoundationx-lfd134x-webassembly-f888c3bb6329653b97738ec35b144d00235e7479ecd2adc3fe53a0089ec3da2e-features -f /tmp/devcontainercli-ubuntu/container-features/0.50.0-1691851552142/Dockerfile.extended /tmp/devcontainercli-ubuntu/empty-folder
[2023-08-12T14:47:50.433Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-ubuntu/container-features/0.50.0-1691851552142 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-linuxfoundationx-lfd134x-webassembly-f888c3bb6329653b97738ec35b144d00235e7479ecd2adc3fe53a0089ec3da2e-features -f /tmp/devcontainercli-ubuntu/container-features/0.50.0-1691851552142/Dockerfile.extended /tmp/devcontainercli-ubuntu/empty-folder
[2023-08-12T14:47:50.433Z]     at oAA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:1066)
[2023-08-12T14:47:50.433Z]     at mK (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:1002)
[2023-08-12T14:47:50.433Z]     at runMicrotasks (<anonymous>)
[2023-08-12T14:47:50.433Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-08-12T14:47:50.433Z]     at async mAA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-08-12T14:47:50.433Z]     at async LC (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-08-12T14:47:50.433Z]     at async jeA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:12219)
[2023-08-12T14:47:50.433Z]     at async _eA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:11960)
[2023-08-12T14:47:50.435Z] Stop (119144 ms): Run in Host: /home/ubuntu/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-407cebbb-675d-4148-bc3e-66d9040618601691851550340 --workspace-folder /home/ubuntu/projects/LinuxFoundationX-LFD134x-WebAssembly --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ubuntu\projects\LinuxFoundationX-LFD134x-WebAssembly --id-label devcontainer.config_file=/home/ubuntu/projects/LinuxFoundationX-LFD134x-WebAssembly/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/projects/LinuxFoundationX-LFD134x-WebAssembly/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-5c483a43-24f1-42f9-9ae5-ebbd169f6924.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-08-12T14:47:50.435Z] Exit code 1
[2023-08-12T14:47:50.437Z] Command failed: /home/ubuntu/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-407cebbb-675d-4148-bc3e-66d9040618601691851550340 --workspace-folder /home/ubuntu/projects/LinuxFoundationX-LFD134x-WebAssembly --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ubuntu\projects\LinuxFoundationX-LFD134x-WebAssembly --id-label devcontainer.config_file=/home/ubuntu/projects/LinuxFoundationX-LFD134x-WebAssembly/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/projects/LinuxFoundationX-LFD134x-WebAssembly/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-5c483a43-24f1-42f9-9ae5-ebbd169f6924.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-08-12T14:47:50.437Z] Exit code 1
[2023-08-12T14:47:53.485Z] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl.localhost\Ubuntu\home\ubuntu\projects\LinuxFoundationX-LFD134x-WebAssembly
[2023-08-12T14:47:53.566Z] Stop (81 ms): Run: wsl -d Ubuntu -e wslpath -u \\wsl.localhost\Ubuntu\home\ubuntu\projects\LinuxFoundationX-LFD134x-WebAssembly
```

I wonder especially about the following lines (it is always the same error, with the respecting version)
```
curl: (22) The requested URL returned error: 404
0.990 
0.992 Error: Could not download Wasmtime version '10.0.1'. See https://github.com/bytecodealliance/wasmtime/releases for a list of available releases
```

other dev container featueres can be installed successfully, e.g.
```
"ghcr.io/rchaganti/vsc-devcontainer-features/wabt:1": {},
or
"devwasm.azurecr.io/dev-wasm/dev-wasm-feature/rust-wasi:0": {},
```

**Comment by brendandburns** [comment]
Apologies for the late reply. You need to add `v` in front of the version, see the example here:

https://github.com/dev-wasm/dev-wasm-c/blob/main/.devcontainer/devcontainer.json#L10

I'd be open to improvements to the script to accept it w/o the `v` also...
